// GitHub repo → Discord channel subscriptions. Each row is one repo watched
// by one guild: its own unguessable webhook token (identifies the row — the
// URL path GitHub POSTs to) and its own HMAC secret (verifies the payload
// really came from GitHub, not just someone who found the URL). Both are
// generated by Sylo, shown once in the dashboard, and pasted into the repo's
// GitHub → Settings → Webhooks page. src/web/routes/githubWebhook.js is the
// receiving end; src/modules/githubAlerts.js formats the payload.
import { randomBytes } from 'node:crypto';
import { prepare, registerPostgresBootstrap, registerPostgresMigration } from './driver.js';

registerPostgresBootstrap(`
  CREATE TABLE IF NOT EXISTS github_watches (
    id             SERIAL PRIMARY KEY,
    guild_id       TEXT NOT NULL,
    repo           TEXT NOT NULL,
    channel_id     TEXT NOT NULL,
    role_id        TEXT,
    changelog_path TEXT,
    token          TEXT NOT NULL,
    secret         TEXT NOT NULL,
    events         TEXT NOT NULL,
    enabled        INTEGER NOT NULL DEFAULT 1,
    created_at     BIGINT NOT NULL
  );
  CREATE UNIQUE INDEX IF NOT EXISTS idx_github_watches_token ON github_watches (token);
  CREATE INDEX IF NOT EXISTS idx_github_watches_guild ON github_watches (guild_id, created_at);
`);
// A Postgres database that was already bootstrapped before these columns
// existed (e.g. sylo-test) needs this to actually gain them — see
// registerPostgresMigration's doc comment in driver.js. Mirrors SQLite
// migrations #40-41 in src/db/index.js.
registerPostgresMigration(40, 'ALTER TABLE github_watches ADD COLUMN IF NOT EXISTS role_id TEXT;');
registerPostgresMigration(41, 'ALTER TABLE github_watches ADD COLUMN IF NOT EXISTS changelog_path TEXT;');

const listStmt = prepare('SELECT * FROM github_watches WHERE guild_id = ? ORDER BY created_at');
const getStmt = prepare('SELECT * FROM github_watches WHERE id = ? AND guild_id = ?');
const byTokenStmt = prepare('SELECT * FROM github_watches WHERE token = ?');
const insertStmt = prepare(
  `
  INSERT INTO github_watches
    (guild_id, repo, channel_id, role_id, changelog_path, token, secret, events, enabled, created_at)
  VALUES
    (@guildId, @repo, @channelId, @roleId, @changelogPath, @token, @secret, @events, 1, @createdAt)
`,
  { returningId: true }
);
const updateStmt = prepare(`
  UPDATE github_watches SET
    channel_id = @channelId, role_id = @roleId, changelog_path = @changelogPath, events = @events
  WHERE id = @id AND guild_id = @guildId
`);
const deleteStmt = prepare('DELETE FROM github_watches WHERE id = ? AND guild_id = ?');
const setEnabledStmt = prepare('UPDATE github_watches SET enabled = ? WHERE id = ? AND guild_id = ?');
const regenSecretStmt = prepare('UPDATE github_watches SET secret = ? WHERE id = ? AND guild_id = ?');
const clearGuildStmt = prepare('DELETE FROM github_watches WHERE guild_id = ?');

function parseEvents(json) {
  try {
    const events = JSON.parse(json);
    return Array.isArray(events) ? events : [];
  } catch {
    return [];
  }
}

function hydrate(row) {
  if (!row) return null;
  return { ...row, events: parseEvents(row.events) };
}

const newToken = () => randomBytes(24).toString('base64url'); // path segment
const newSecret = () => randomBytes(32).toString('hex'); // HMAC key

export async function listGithubWatches(guildId) {
  return (await listStmt.all(guildId)).map(hydrate);
}

export async function getGithubWatch(guildId, id) {
  return hydrate(await getStmt.get(id, guildId));
}

/** Looked up per inbound webhook POST — the token in the URL path. */
export async function getGithubWatchByToken(token) {
  return hydrate(await byTokenStmt.get(token));
}

/**
 * @param {string} guildId
 * @param {{ repo: string, channelId: string, roleId?: string, changelogPath?: string, events: string[] }} w
 * @returns {Promise<number>} the new row's id
 */
export async function createGithubWatch(guildId, w) {
  const result = await insertStmt.run({
    guildId,
    repo: w.repo,
    channelId: w.channelId,
    roleId: w.roleId || null,
    changelogPath: w.changelogPath || null,
    token: newToken(),
    secret: newSecret(),
    events: JSON.stringify(w.events ?? []),
    createdAt: Date.now(),
  });
  return result.lastInsertRowid;
}

export async function updateGithubWatch(guildId, id, w) {
  await updateStmt.run({
    guildId,
    id,
    channelId: w.channelId,
    roleId: w.roleId || null,
    changelogPath: w.changelogPath || null,
    events: JSON.stringify(w.events ?? []),
  });
}

export async function deleteGithubWatch(guildId, id) {
  await deleteStmt.run(id, guildId);
}

export async function setGithubWatchEnabled(guildId, id, enabled) {
  await setEnabledStmt.run(enabled ? 1 : 0, id, guildId);
}

/** Issue a fresh secret (the old one, and anything signed with it, stops working). */
export async function regenerateGithubWatchSecret(guildId, id) {
  const secret = newSecret();
  await regenSecretStmt.run(secret, id, guildId);
  return secret;
}

/** Drop every watch for a guild (guild purge). */
export async function clearGuildGithubWatches(guildId) {
  await clearGuildStmt.run(guildId);
}
